/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rtsa_http_server_source.h) */
/* BINDTOOL_HEADER_FILE_HASH(782e41b0790cbd59f16ea1d6eabd0e5e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aaronia_rtsa/rtsa_http_server_source.h>
// pydoc.h is automatically generated in the build directory
#include <rtsa_http_server_source_pydoc.h>

void bind_rtsa_http_server_source(py::module& m)
{

    using rtsa_http_server_source = ::gr::aaronia_rtsa::rtsa_http_server_source;


    py::class_<rtsa_http_server_source,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<rtsa_http_server_source>>(
        m, "rtsa_http_server_source", D(rtsa_http_server_source))

        .def(py::init(&rtsa_http_server_source::make),
             py::arg("arg0"),
             py::arg("demod_block"),
             py::arg("spectran_block"),
             py::arg("samp_rate"),
             py::arg("tune_spectran_fc"),
             py::arg("tune_spectran_fc_offset"),
             py::arg("iq_demod_fc"),
             D(rtsa_http_server_source, make))


        .def("set_freq",
             &rtsa_http_server_source::set_freq,
             py::arg("freq_hz"),
             D(rtsa_http_server_source, set_freq))

        ;
}
