/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-aaronia_rtsa
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_AARONIA_RTSA_API_H
#define INCLUDED_AARONIA_RTSA_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_aaronia_rtsa_EXPORTS
#define AARONIA_RTSA_API __GR_ATTR_EXPORT
#else
#define AARONIA_RTSA_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_AARONIA_RTSA_API_H */
